# kubernetes/0_station_secret.yaml
#
# This file holds the SSH password for the SDR host.
# Your API would create this, filling in a secure, random password.
#
apiVersion: v1
kind: Secret
metadata:
  # This name MUST match the 'station-name' used in the other files
  name: station-a-secret
  # This namespace MUST match the 'station-name'
  namespace: station-a
type: Opaque
stringData:
  # These are the env vars your entrypoint.sh expects
  CORECAST_SSH_USER: "corecast-host-a"
  CORECAST_HOST_PASSWORD: "REPLACE-THIS-WITH-A-RANDOM-PASSWORD"
